### ISSUE TITLE
Shared file system between ingest and storage - what is the correct AWS approach?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1140]
The amount of content deposited into Merritt varies significantly from week to week.  Deposits from each campus are sporadic and project-driven.  One week in May 2022, we had 19TB of content deposited.

When a campus does initiate a large ingest, our current provisioned I/O is overwhelmed by the content.

What access this shared content
- 3 Ingest Servers: download from campus/cloud, write to disk, fixity check content
- 2 Storage Servers: read from disk, upload to S3 compatible storage (may or may not be S3)

## Past implementations

- Each server had dedicated EBS volume
  - Single server EBS was too limiting and required us to make an extra copy of content
  - EBS volumes frequently ran out of space

## Options

- EFS has been too slow and possibly too expensive
- Shared EBS
- Multi-attach EBS volume with GlusterFS
- Lustre FS
  - Ashley will read up on this  
- Other options?
- Co-locate Ingest and Storage with single large EBS
  - this may have other limitations
  - harder to containerize

What would AWS recommend?

Martin will add this to the agenda for an IAS conversation with Kevin 

---
## Workflow
- Ingest reads a manifest
- Ingest downloads content from campus data centers or cloud providers
- Ingest wites content to EFS
- Ingest performs fixity check (checksum) from EFS
- Ingest creates an ingest manifest
- Storage reads ingest manifest
- Storage loads content to S3-compatible service (often not AWS)
- Storage performs checksum on cloud storage copy
- Content is deleted from EFS

## File System Needs

- Previously used EBS
  - Forced us to make an extra copy of the content
  - At critical times, we would fill disks 
- Scalable size (suggests EFS)
  - File system returns to empty on a regular basis 
  - Files reside on the FS until they are loaded to S3 and verified
  - Failed jobs remain on disk until investigated and resolved
    - Restarts often need to re-download content to a new folder
  - Question: what is the largest size our EFS has reached in the last year?
    - Only a couple months of data are accessible.  The size has grown as high as 7.3T. 
  - In one week in May, we processed 18T in the week 
  - Based on this, I would presume we would want 10-20T if we had to provision a specific amount (my guess)
    - it would be good to validate this against the EFS size in the past year 
- Shared by 7 hosts
  - This is expected to grow as Merritt deposits scale up
  - Needs to be shareable with servers or containers
- Performant as it scales
  - Since the content is transient, it needs to perform well even when the file system is empty
  - Ideally we could scale up the number of servers to process more content
  - Currently, EFS performance is dictating a maximum number of hosts 

## Options
- EFS with provisioned throughput
  - At peak periods dynamically raise/lower throughput in response to processing needs 
    - How dynamic could this be
  - At peak periods, dynamically scale ingest and storage instances (container or servers)
- FSx provisioned to adequately handle peak processing
- FSx - dynamically provisioned to match processing needs (4T to ??T)

**Comment by terrywbrady** [comment]
## 7/27 - Meeting with IAS and AWS Reps

- Consider FSx for ZFS (compatible with nfs v3 client)
  - Must provision space
  - Must provision throughput

## Refactoring consideration
- Consider dynamic creation and mounting of file systems on demand
  - Really need a good size estimate for this to be successful   
- Consider using S3 instead of a file system
  - Slower throughput for individual, but scales indefinitely
    - Could possibly process many operations with lambda 
    - Space allocation is dynamic
    - No penalty for parallel operations

**Comment by terrywbrady** [comment]
What about allocating specific file systems for priority collections?

**Comment by ashleygould** [comment]
## Estimates for ZFS changes

- https://aws.amazon.com/fsx/openzfs/pricing/

```
SSD storage capacity:   $0.090 per GB-month
Throughput capacity:    $0.260 per MBps-month
SSD IOPS:               $0.0060 per IOPS-month
```

Assume you want to store 5 TB of general-purpose file data using SSD storage in
the US West Region.  Provision a 5 TB Single-AZ file system with 256 MB/s of
throughput capacity.
```
Storage:        5 TB x $0.09 per GB-month       = $461/mo
IOPs:           15360 (3 per GB storage)        =   $0/mo
Throughput:     256 MB/s x $0.26 per MB/s-month =  $67/mo

Total monthly charge:                             $528/mo
```

10TB SSD storage
```
Storage:        10 TB x $0.09 per GB-month      = $922/mo
IOPs:           30720 (3 per GB storage)        =   $0/mo
Throughput:     256 MB/s x $0.26 per MB/s-month =  $67/mo

Total monthly charge:                             $989/mo
```

**Comment by ashleygould** [comment]
### Testing zfs on stage

I am working with IAS to create a 2 TB ZFS volume.  On each of the `uc3-mrt-ingest-stg` and uc3-mrt-store-stg` hosts. We will mount this volume on `/apps/ingest-stg-zfs`.  Once ready, Mark will reconfigure `uc3-mrt-ingest-stg` to write data to this new mount point and restart ingest.  Merritt team will then load some large ingests into stage to see how the new volume performs.

**Comment by mreyescdl** [comment]
Stage Ingest and Storage are now using shared ZFS disk.

**Comment by elopatin-uc3** [comment]
@terrywbrady we talked about status of ZFS testing on stage in today's (8/15) team meeting. Ashley brought up an aspect of ZFS that we were not yet aware of, called thin provisioning. This type of provisioning allows for setting a top end of the ZFS allocation, but also then allows for one-way growth beyond that in case a large submission breaches the initially specified allocation limit. 

@mreyescdl is going to allow the current test ingest complete on stage (Nuxeo UCM San Joaquin collection content). Then with a small 100GB ZFS allocation set and thin provisioning active, we'll start a new test to observe this type of provisioning in action and collect test data. @ashleygould is also going to discuss temporarily setting ingest hosts to m5.large on stage with IAS for use during this test, as we've observed significant CPU I/O wait on the smaller existing hosts are are unsure if this is due to lack of network bandwidth or if it's disk access related.

**Comment by ashleygould** [comment]
Mark tested with a large submission and results were better than EFS, but 
ingest instances had high CPU IOWait.  Stage instances are t3.small for ingest and
m5.large for store.

next steps:
- OPS: research instance types and IO throughput
- OPS: research zfs thin provissioning more
- IAS: set up a thin provissioned volume on stage
- IAS: set up librato monitoring on zfs instance 
- IAS: change instance type on one of the ingest stage nodes to m5.large
- OPS/MRT: make script to swap mountpoints on ingest nodes
- OPS: reboot ingest nodes prior to re-run
- MRT: re-run large submission
- OPS: capture ec2 stats:
  - IO throughput
  - NFS throughput
  - cpu iowait
  - network throughput
  - network throttling (ethtool)

**Comment by ashleygould** [comment]
Update:

thin-provissioning is a bust. Does not do what we were hoping for.  So we did not create a new ZFS filesystem.  We will continue to test on the existing one.

Librato does not support FSx service, so not dashboards.

But - Martin Haye set up a cloudwatch dashboard for us:
[https://cloudwatch.amazonaws.com/dashboard.html?dashboard=UC3_ZFS_fs-0b9822a1af853be7a_Da[…]NDMxLTRiYWEtOWYwMC0xZTZlMjU3NjkwODciLCJNIjoiUHVibGljIn0=](https://cloudwatch.amazonaws.com/dashboard.html?dashboard=UC3_ZFS_fs-0b9822a1af853be7a_Dashboard&context=eyJSIjoidXMtZWFzdC0xIiwiRCI6ImN3LWRiLTQ1MTgyNjkxNDE1NyIsIlUiOiJ1cy1lYXN0LTFfVDFJaU1UUHZZIiwiQyI6IjQyc2c3dmo2bDYwcThja2c5ZTlnNnFnbHJlIiwiSSI6InVzLWVhc3QtMTozZjJmZWViNS1iNDMxLTRiYWEtOWYwMC0xZTZlMjU3NjkwODciLCJNIjoiUHVibGljIn0=)
You have to click on the "options" and select the sample period.  Otherwise it selects one for you, but does not tell you what it is.  

Martin changed ec2 instance type on one of the uc3-mrt-ingest-stg hosts to c5n.large.  This should give us much better network bandwidth, which I think may have been the bottle neck in the first trial.

**Comment by mreyescdl** [comment]
@ashleygould ZFS testing started on Stage - expect TBs of data to be submitted to Ingest workers over the next few days 
Workers now => (01 - c5n.large, 02 - t2.small)

**Comment by mreyescdl** [comment]
Ingest is having problems removing payload directory

```
[error] HandlerCleanup: Failure in removing: /dpr2/ingest_home/queue/bid-bd2f4790-bc24-412f-94d6-d7c37ce341e0/jid-1aa018ba-86d0-4fb3-9b91-64025ecd4993/producer   Continuing
```

**Comment by mreyescdl** [comment]
Problem was in the Manifest processor in core library.  Valid manifest payload did not trigger error, but regular file payload would.
Here is fix.  
https://github.com/CDLUC3/mrt-core2/pull/16

**Comment by elopatin-uc3** [comment]
Thanks for finding the root cause for this @mreyescdl

**Comment by mreyescdl** [comment]
Legacy EFS Stage disk contents (fs-6fe432c4.efs)

$ du -sh *
3.2G    dataone
211M    frontera
219G    ingest_home
31G     palestinian_museum
716K    terry

I'll cleanup the `ingest_home` disk and move the rest to new ZFS disk.  
Please remove any data if not needed @terrywbrady @elopatin-uc3

**Comment by terrywbrady** [comment]
@mreyescdl , I deleted the terry directory.  I think @elopatin-uc3 will need to weigh in on the others.

**Comment by mreyescdl** [comment]
IAS request made to decommission Stage EFS and to reduce IO Throughput on prod

```
- Decommission EFS disk fs-6fe432c4.efs.us-west-2.amazonaws.com which is mounted
on Stage Ingest and Storage workers

- Reduce IO throughput on EFS production disk
fs-3b22fd91.efs.us-west-2.amazonaws.com from 50MB/s to 10MB/s
```
