### ISSUE TITLE
Dryad/Wasabi Cleanup - Failure on Delete of object from node

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1171]
{"error"=>"execution expired for delete/2001/ark%3A%2F13030%2Fm57x1fhb"}
I do not know if the lambda is timing out on an especially large object.
:heavy_check_mark:
1

[9:22](https://cdlib.slack.com/archives/C86U0VBLH/p1658938952106299)
This may have started the errors
Wed Jul 27 08:22:22 PDT 2022 ** (00) [replic] DBUtil: getOperation - Exception - cmd=select inv_versions.number from inv_objects, inv_files, inv_versions where inv_objects.ark='ark:/13030/m57x1fhb' and inv_files.pathname='producer/O'BrienEtAl_HammingDistanceValues.xlsx' and inv_versions.number <= 2 and inv_files.billable_size > 0 and inv_files.inv_object_id = inv_objects.id and inv_versions.id = inv_files.inv_version_id ORDER BY inv_versions.number DESC LIMIT 1; - exception:java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BrienEtAl_HammingDistanceValues.xlsx' and inv_versions.number <= 2 and inv_files' at line 1

**Comment by dloy** [comment]
A tool in mrt-inventory is used to build the key of the file to be deleted.  The code InvDBUtil.getAccessVersionNum used a String version of the MySQL handling that contained embedded single quote for the pathname being looked up.

The code in mrt-inventory has been changed to use a PreparedStatement instead - that allows the code to determine how to handle the specific file pathname being supplied.  The change works and has allowed a manual delete of the specific object above. 

Because multiple objects appear to have this problem and emergency release of replic is required to permanently fix this specific problem
