### ISSUE TITLE
Stop CPU load alerts for store servers

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1186]

**Comment by elopatin-uc3** [comment]
Is there a stress condition we should be addressing, beyond the expected heavy CPU usage?
- I/O bound CPU would be good to have an alert for (caused by high swap usage or access to EFS).
- Could we ask IAS to set up an EFS-based alert? Joe has a new sample alert for Ingest: "uc3-ingest-prd_hosts_CpuIoWait"
- Ashley will talk with IAS about addition of I/O wait alerts and conditions around this (e.g. duration of an hour)

**Comment by terrywbrady** [comment]
Ashley disabled active checks for this service through Nagios.  Did not require coordination iwth IAS/
