### ISSUE TITLE
[SWORD] Incorrect response code when Ingest ALB times out 

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1228]
Switching to the Ingest ALB creates a timeout limitation of 66 minutes.
If Dryad submission exceed this, Sword throws the 504 error listed below.

Let's catch this error and respond to Dryad with a 202 (Accepted) 
This will allow Dryad to know that Merritt is still processing the request asynchronously

```
org.swordapp.server.SwordError: Ingest handling failure url='http://ingest-prd.cdlib.org:33121/update-object' Exception:org.swordapp.server.action.IngestHandler-setIngestResponse:275 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - responseCode:504
        at org.swordapp.server.action.IngestHandler.process(IngestHandler.java:133)
```

**Comment by dloy** [comment]
The timeout error 504 is correct to this particular event: gateway time.

In this situation we understand that the process "probably" continued and completed, so a 202 is accurate. Unfortunately 202 is not an exception but a successful completion of the process even though the system views as an exception.

In this case even though a 504 exception occurred the returned status was 400, which is an error.

After conferring with Scott, he was OK with the 504 exception. The code was corrected to return the 504 status to Dryad instead of the 400.
