### ISSUE TITLE
While bulk loading Pal Museum content, approx 7% of jobs are deadlocking in inventory

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1323]
We have a total of 150,000 jobs to submit

```
Looks like most of the exceptions were: Thu Dec 15 15:07:02 PST 2022 ** (02) [yyMMdd] SaveObject: Exception for entry id=ark:/13030/m52k3pbr - Exception:org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='501',inv_object_id='3599336' - exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
:thankyou:
2

[4:53](https://cdlib.slack.com/archives/C86U0VBLH/p1671151987923489)
The deadlock should not have happened with the current locking we're using.  Another error only occasionally: Error during HttpClient processing - timeout:3600000 -
```

**Comment by dloy** [comment]
This locking error is specific to setting the inv_collections_inv_objects value.
~~~
Thu Dec 15 13:09:24 PST 2022 ** (02) [yyMMdd] SaveObject: Exception for entry id=ark:/13030/qt4q00x5f5 - Exception:org.cdlib.mrt.utility.HTTPUtil-getObjectEntity:219 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - timeout:3600000 - URL:http://storage.cdlib.org:35121/content/5001/ark%3A%2F13030%2Fqt4q00x5f5/0/system%2Fmrt-owner.txt?fixity=no - responseCode:502
Thu Dec 15 14:39:26 PST 2022 ** (02) [yyMMdd] SaveObject: Exception for entry id=ark:/13030/m53r849m - Exception:org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='501',inv_object_id='3599088' - exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
Thu Dec 15 14:39:26 PST 2022 ** (02) [yyMMdd] SaveObject: Exception for entry id=ark:/13030/m5v76w3x - Exception:org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='501',inv_object_id='3599089' - exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
~~~

The locking problem occurred because a large number of relatively small object were new, submitted together and concurrently attempting to update the inv_collections_inv_objects table.

The table gets updated only if the object is not already part of the collection - new. 

This particular table entry is one of the last processes performed by SaveObject. A fairly easy fix is to remove the entry from commit handling. If the entry is required after the commit is successful then do an autocommit insert as one of the last steps in the process.  No other tables are dependent on the presents of the entry in this table - Foreign constraints. 

This update can be incorporated as part of the current BOM release with fairly high priority after the break - probably a 2 day fix.

**Comment by elopatin-uc3** [comment]
Consider making threadpool smaller for inventory? (currently 5)

**Comment by dloy** [comment]
Additional work is needed to determine if table lock escalation occurred above. 

Supposedly with InnoDB, which inv_collections_inv_objects has (ENGINE=InnoDB) escalation should not occur: "The lock information in InnoDB is stored space-efficiently so that lock escalation is not needed. Typically, several users are permitted to lock every row in InnoDB tables, or any random subset of the rows, without causing InnoDB memory exhaustion" (https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-model.html)

If escalation is the cause, see this article is from 2022.:
https://learn.microsoft.com/en-us/troubleshoot/sql/performance/resolve-blocking-problems-caused-lock-escalation

The section on "holding an incompatible table lock" offers a general solution to escalated table locks.

For general discussion version 8 see:
https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html#:~:text=You%20can%20get%20deadlocks%20even,the%20row%20inserted%20or%20deleted.

Simplest approach looks like retry with variable high delay times:
AddObject retries in mrt_inventory.

**Comment by elopatin-uc3** [comment]
Test on stage with submission of ~500 PM objects.
