### ISSUE TITLE
[INGEST] Queue redesign (Part 3) - Support additional zookeeper states

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1441]
We need additional states for Ingest entries e.g. recording, processing.
This is for Job queue only.

**Comment by elopatin-uc3** [comment]
Latest notes: https://github.com/CDLUC3/mrt-doc/blob/main/design/queue-2023/states.md

**Comment by mreyescdl** [comment]
Initial work for supporting multiple states is working on Ingest Stage under the "queue_LIB" branch.
Scale testing is complete.   Edge case testing is not.

I'll start work on supporting HOLD and LOCK which is under ticket https://github.com/CDLUC3/mrt-doc/issues/1883
This will further test the ZK library.  Once this work is complete I'll circle back to this ticket for more testing

**Comment by mreyescdl** [comment]
There was an issue with Ingest Unit test involving a the method `ingestState.setServiceName(serviceNameS);`
This method is instantiated when creating a ProcessManager from the Unit Test.  The error involves Zookeeper Session expiration when querying if the Ingest Queue is frozen.
Now that the thaw/frozen state is stored in ZK and not the file system, this is a ZK call.  The Unit test tries to make this call, but gets the expiration exception.

For now, Ingest is fault tolerant and assumes this exception is from the Unit Test.
In ProcessManager.java...
```
                try {
                   zooKeeper = new ZooKeeper(queueConnectionString, sessionTimeout, new Ignorer());
                } catch (Exception e) {
                   // Unit test catch
                   unitTest = true;
                }
```

@terrywbrady Can we discuss a more permanent fix?

**Comment by terrywbrady** [comment]
I have a couple of ideas.

We could probably figure out a way to detect if the tests are running.  I suspect that JUnit sets a property when tests are running.

If that property is enabled, then you could bypass initializing the ZooKeeper.  I will do a bit of testing to see if I can find a property.

If you want to keep the logic that you have in place, I recommend trapping the specific ZooKeeper Exception that is thrown rather than trapping "Exception". Maybe add a few more comments as well. Rather than setting a variable "unitTest", you could just check if zooKeeper is null.
________________________________
