### ISSUE TITLE
[INGEST]  EZID minting of culled identifiers

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1465]
From Slack:

```
If we attempt to create the ARK after it has been removed, then we see a "already in use" error, even though it is not visible when querying the ARK.
It seems inconsistent:
  query for the ark --> does not exist
  create the ark  --> already in use
```

Ephemeral Shoulder - ark:/99999/fk4
Permanent Shoulder - ark:/99999/fk8

**Comment by mreyescdl** [comment]
Now testing permanent shoulder in EZID stage.

Question:  Should Merritt Stage be talking to EZID stage ??

**Comment by marisastrong** [comment]
What are the use cases for utilizing EZID stage?
When does Merritt create/mint identifiers (stage, production) during testing?
Merritt/EZID is meeting to clarify use cases and determine best practices going forward

**Comment by marisastrong** [comment]
**Background**
5/18/23 Dryad reported errors when submitting content in their stage environment.  The error occurs when Merritt is trying to use an identifier that is "ephemeral" (used before but now expired).  Merritt has assumed they can reuse the identifier once it has expired as this was not the behavior in the past.   It has been resulting in an error.  

EZID has discovered when deleting expiring ids, not everything is cleaned up.  However, this shouldn't prevent recreate of an identifier.  The create(id) operation expects an identifier to be provided.  Minting operation returns an identifer.  Create doesn't go through minting.  User create anything in the EZID db.  After the test identifier expired EZID didn't clean up properly.

Option to use ezid-stage was offered however the identifiers exist in the EZID production db and any updates to current test identifiers would fail since they would not exist in the EZID stage db.   There is work to remove/reassign content on the Merritt side and the EZID side.  
  
EZID needs to make sure the test identifiers are fully deleted from the db. 
fk8/ 
No delete is run from Merritt - they won't be deleted.  Can create new, can update existing.

For future, can sync up EZID stage db to match that of EZID prod db in order to utilize /fk8

**Next steps**
- [ ] understand from Dryad what the impact is for failures in the stage environment (what is their use case and impact) @marisastrong 
- [ ] EZID team will do analysis on the clean up after the expiration of an identifier and work to retain functionality that used to exist
- [ ] longer term solution will be to have an end to end integration across all stage environments.  This relies on a production to stage database sync to bring over theproduction identifiers to the stage environment.  Would /fk4 or /fk8 be used in the new stage environment going forward?  /fk8 is what is in production so it would be migrated to stage db.

**Comment by jsjiang** [comment]
Just want to confirm two things:
1.  Did you use the POST or PUT method when creating the ARK ID in question 
2. Is this the error message you received - "error: bad request - identifier already exists"

FYI. We logged this issue in [EZID/issues/387](https://github.com/CDLUC3/ezid/issues/387)
Jing

**Comment by mreyescdl** [comment]
@jsjiang I'm not sure about the POST or PUT request, but I can find out.
However, that is the error message we receive.

Thanks for looking into this issue.

-Mark

**Comment by marisastrong** [comment]
The impact on Dryad: Submissions to our staging system were not going through. Users would complete a submission, but it would not be available for curation or other processing. All of these are test submissions, but sometimes the tests are done as part of live demos for Dryad member institutions (or prospective members), so failures can be quite visible. Test submissions may also be performed by members who want to understand functionality, as part of curator training, or by developers trying to replicate an issue.

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark, 
I went back to the original issue report and found out that you were using PUT for creating an identifier. The information is good enough for troubleshooting. 
Thank you

Jing

**Comment by mreyescdl** [comment]
Actions for short term fix:
- Deleted content from two active Dryad Stage collections
  - cdl_dryaddev_content
  - cdl_dryadstg_content
  
- Switch these collection to use permanent shoulder located on EZID stage host

**Comment by mreyescdl** [comment]
Switch complete. 
Ryan has sync'd their DB and tested the new configuration.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
