### ISSUE TITLE
Consolidate the versioning of maven plugins - can the BOM do this?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1482]
This may not be possible.  I tried to treat the pluginManagement like the depenedencyManagement block, but I did not have any luck.  David might have some ideas about whether or not this is possible.

## Essential Plugins - Please Create Variables
- **maven-compiler-plugin**
  - please name the variable maven.compiler.plugin.version
- **docker-maven-plugin** (docker integration stack)
- **maven-failsafe-plugin** (integration tests)
- **maven-surefire-plugin** (unit tests)

## Suspect Plugins - Only Create a Variable if these are Essential
- **jacoco-maven-plugin** (coverage reporting)
  - we should consider dropping this 
- **maven-assembly-plugin** 
  - why is this needed?  Could we drop this?
  - this is used for the boxrun code, but that should no longer be in mrt-cloud
- **maven-shade-plugin**
  - use by node-test
  - is node-test still needed?   If not, please delete the directory.  We have github history if needed.
- **maven-antrun-plugin**
  - this is in mrt-core2
  - why do we need this?
  - please eliminate if possible
  - also used in ingest
- **maven-project-info-reports-plugin**
  - in mrt-zoo
  - is this still needed?
  - please delete if this is not longer needed  
  - also used in inventory
  - also used in replication
  - also used in store
- **maven-dependency-plugin**
  - used by store, what is special about store that requires this?

**Comment by dloy** [comment]
# Using parent pom.xml properties

This approach provides a mechanism similar to a BOM for setting common values across multiple remote pom.xml in multiple services. In this case - setting the compiler version number. This approach could be used for setting dependency values but BOM handles dependency versions far more successfully and should not be replaced.

A parent pom.xml provides a way to shorthand in a child the use of ALL build functions in a parent. The child only has limited ability to restrict parent usage in the child.

If the parent contains only property values then the child pom.xml may use or not use the parent value.  All unused properties in the parent are ignored. The local declaration of a property in the child is used instead of the parent.

## Example

### Parent pom.xml
~~~
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cdlib.mrt</groupId>
    <artifactId>mrt-parent-properties</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>mrt-parent-plugin</name>

    
    <!-- force UTF-8 -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <compiler.java>1.8</compiler.java>
        <compiler.version>3.9.0</compiler.version>
        <unused.prop>unused</unused.prop>
    </properties>
</project>
~~~

__Description__
Note this pom.xml only contains properties and nothing else. This allows the parent to be used across multiple pom.xml as a mechanism for passing common properties without forcing the use of a specific plugin.

### Child pom.xml
~~~
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cdlib.mrt</groupId>
    <artifactId>mrt-logging</artifactId>
    <version>2.0-SNAPSHOT</version>
    <name>UC3-mrtLogging</name>
    <url>http://uc3.cdlib.org</url>
    
    <parent>
        <groupId>org.cdlib.mrt</groupId>
        <artifactId>mrt-parent-properties</artifactId>
        <version>1.0.0</version>
    </parent>
  
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.cdlib.mrt</groupId>
                <artifactId>mrt-reflectoring-bom</artifactId>
                <version>1.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    
    <properties>
        <war.version>3.8</war.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler.version}</version>
                <configuration>
                    <source>${compiler.java}</source>
                    <target>${compiler.java}</target>
                    <compilerArgument>${compilerArgument}</compilerArgument>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.cdlib.mrt</groupId>
            <artifactId>mrt-json</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.cdlib.mrt</groupId>
            <artifactId>mrt-core</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-ssm</artifactId>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
      
           <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>2.20.0</version>
              </dependency>
              
            <dependency>
              <groupId>org.apache.logging.log4j</groupId>
              <artifactId>log4j-core</artifactId>
              <version>2.20.0</version>
            </dependency>
...
    </dependencies>

</project>
~~~

__ Description__
Important things to note in the child pom.xml:
- the following links the child to the parent. The parent pom.xml works similar to a BOM and can be called remotely.
~~~
    <parent>
        <groupId>org.cdlib.mrt</groupId>
        <artifactId>mrt-parent-properties</artifactId>
        <version>1.0.0</version>
    </parent>
~~~
- parent property will be used for setting child value:
~~~
                <version>${compiler.version}</version>
~~~
Note the parent property can be used anywhere in the child pom.xml

- the parent <unused.prop> is not used in the child. It is ignored and no error occurs

- BOM and parent properties are both used together

This approach can be used for globally setting build function versions across multiple microservice pom.xml's

**Comment by dloy** [comment]
The problem with the above approach is that the parent module cannot be built as part of using 
~~~
<modules>
   <module>...</module>
   <module>...</module>
<modules>
~~~ 
if any child modules use the parent. 

Maven defaults to a recursive tests of called module builds and their called module builds (etc). If any is a child module a failure occurs.

One solution uses two mvn builds. The first mvn constructs only the parent module and the 2nd for everything else.

The question at this point is whether updating the merritt Jenkins projects to use 2 mvn builds is worth the shared properties across all pom plugins. 

At this point opensearch1 branch is broken because of the need for the 2nd build.

**Comment by dloy** [comment]
Decision is to continue with the two mvn command mechanism.

This includes changes to mrt-core-int-test-all and Jenkinsfile updates to all microservice deploys to initialize the core2/parparm and the rest of all services with dependencies
