### ISSUE TITLE
Stop making local copies

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#15]
Making local copies limits the size of objects we can handle, introduces
complexity (e.g. locking ingest jobs to servers), probably increases costs
(storage on each server), and may reduce performance (at least in some
scenarios).

## Questions/Action Items

Questions:

- In the past we've said we have to make local copies because services / the network are
  unreliable.
  - just how unreliable are they? can we quantify that?
  - where can we mitigate w/retries etc., and where is that not possible?

Straw proposal:

- Ingest
  - stream uploads directly to S3 (even for collections where S3 is not primary)
  - return S3 URLs instead of ingest server URLs
- Storage
  - uploads:
    - abstract move/copy/store operation across different combinations of storage:
      - S3 -> same S3 bucket: no-op
      - S3 -> different S3 bucket: use s3 sync, verify, delete
      - S3 -> OpenStack: stream instead of making local copy
        - maybe use [rclone](https://rclone.org/)?
      - S3 -> Cloudhost: stream instead of making local copy
        - create [pre-signed URL](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html)
          & pull from Cloudhost side?
    - downloads:
      - Use `ZipOutputStream` to stream large zip files directly to network
- Audit
  - stream directly from storage
- Replication
  - from S3: see above under storage/uploads
  - OpenStack -> S3: stream instead of making local copy
    - maybe use [rclone](https://rclone.org/)?
  - Cloudhost -> S3: just don't support it?

Alternatives / other areas to explore:

- use [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon)
  to provide an S3-backed "local" filesystem
- look at [Dat](http://datproject.org/) and/or other alternatives to straight HTTP
  for large file transfers

Are there other issues unique to each service that need to be addressed?

**Comment by dloy** [comment]
***Reliability of cloud requests
Clouds have two basic problems:
- Load on a cloud service can block http actions
- Completion back to a program of an http action does not necessarily mean that the operation is complete.

Load failures require multiple retries. Unfortunately, the failure can occur on almost every part of a transaction.  For SDSC this failure was 1 in 7. For AWS, this failure is between 1 in 20 - harder to determine because java API does it automatically. Very rarely do 4 retries fail - logic was built in to expand this to 8 under very rare conditions.

When a cloud transaction completes processing back to a program, the cloud service (also true of NFS) may not have completely distributed knowledge of that transaction. Issue a write and follow it by a metadata test (POST, HEADER) has a high chancel of failure because not all cloud enterprise hosts are yet in sync.

These two problems make for some weird programming where almost everything has a retry.


***Not all Merritt content requires local queuing.

Some of the issues involved are:
* Is a fixity check required before returning content:
yes - queued
no - direct stream
This also impacts copy functions (saving content from ingest and copying from one node to another) which were initially performed using non-queued. This was changed to queued for two reasons, needing to perform fixity but more importantly for being able to restart parts of copying. If the copy blew out after 6G, the copy could then be restarted at the point it failed. Once a complete queued version existed then saving the content (after fixity) was possible.

Storing content to a cloud (upload) has the additional problem that large content needs to be segmented. For segmenting, queuing is required. 

* Is output saved asynchronously:
yes - queued
no - direct stream.

For audit: 
a non-fixity test for getting content then performs it's own fixity test - no queuing.

For storage:
Direct return of container content is non-queued - async queued.
Direct return of file content is not queued if no-fixity is set

For replication:
All content is queued because of both fixity testing and because copy may required multiple part actions

Note:
Because storage uses a java interface for handling AWS S3 it's unknown how the interface works with the data before received in storage as an InputStream.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think we have essentially implemented this

**Comment by elopatin-uc3** [comment]
Closing as we've made significant progress toward use of fewer local copies for a variety of operations.
