### ISSUE TITLE
admin: SSM Quota - evaluate efficiency of calls in admin tool.  If issues persist, ask IAS about increasing API quota

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1504]
https://docs.aws.amazon.com/general/latest/gr/ssm.html

https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html

**Comment by terrywbrady** [comment]
Our lambda (built in docker) does not seem to have the layer referenced here: https://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/

One possible solution:
- On start up, look in for /tmp/colladmin.yml
- If it exists and it is less than X min old, resolve it
- Otherwise, read config from source and resolve

This probably will necessitate separating the config to a cache-able and non cache-able one.

**Comment by terrywbrady** [comment]
Brian suggested saving to the ENV.  This works across lambda executions!
```
        cval = ENV.fetch('CONFCACHE_CVAL', '')
        if cval.empty? || Time.now - Time.new(cval) > 120
          ENV['CONFCACHE_CVAL'] = Time.now.to_s
        end
        LambdaBase.log_config(config, "CTIME: #{ENV.fetch('CONFCACHE_CVAL', '')}")

```
