### ISSUE TITLE
ETD Stage host: etds user no longer has sufficient git permissions

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1535]
Ashley reset permissions to the correct role account and also ensured directories are no longer group writable, which should safeguard us from accidentally switching permissions on files in the git working tree.

**Comment by ashleygould** [comment]
resolved

The problems I saw were mostly under the git working tree at /etds/apps/uc3-etds .  It looked like various merritt team users ran git pull , and because directories are group writable, this created many files/dirs not owned by etds.all files/dirs under /etds are now owned by etds:etds and all directories are no longer group writable.  When team members with to run git pull, they must become the etds user first.
[5:13](https://cdlib.slack.com/archives/C86U0VBLH/p1689639207198539)
I have also set the umask for user etds to 0022.  this is configured by puppet in file /etds/.profile.d/etds_umask.sh
