### ISSUE TITLE
Logstash Failure of Store Stage

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1647]
```
Oct 20 16:51:19 uc3-opslogstash01x2-stg logstash[17300]: [2023-10-20T16:51:19,468][WARN ][logstash.outputs.opensearch][opensearch-uc3][599d2db729d7fd192ee3fe82cecffd031804bd300f6be0f66b8c4671b920de0e] Could not index event to OpenSearch. {:status=>400, :action=>["create", {:_id=>nil, :_index=>"filebeat-uc3-mrt-stg", :routing=>nil}, {"event"=>{"original"=>"\t\"\\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)\","}, "cdl"=>{"program"=>"uc3", "environment"=>"stg", "fqsn"=>"uc3-mrt-store-stg", "subservice"=>"uc3-mrt-store", "service"=>"uc3-mrt"}, "ecs"=>{"version"=>"8.0.0"}, "tags"=>["store", "beats_input_codec_plain_applied"], "message"=>"\t\"\\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)\",", "input"=>{"type"=>"log"}, "@timestamp"=>2023-10-20T23:51:17.915Z, "log"=>{"file"=>{"path"=>"/apps/dpr2store/apps/mrt-store/current/logs/log4j-ecs-json.log"}, "offset"=>1791982}, "json"=>{}, "@version"=>"1", "agent"=>{"version"=>"8.10.2", "id"=>"c133ed05-c3cf-4814-a330-5b7b422db0e0", "ephemeral_id"=>"7efecf06-b1ae-43d8-91af-ed23f82c1d90", "name"=>"uc3-mrtstore01x2-stg.cdlib.org", "type"=>"filebeat"}, "host"=>{"name"=>"uc3-mrtstore01x2-stg.cdlib.org"}}], :response=>{"create"=>{"_index"=>".ds-filebeat-uc3-mrt-stg-000013", "_id"=>"xcCAT4sBOPVCxsDEISHd", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"documents must contain a single-valued timestamp field 'json.@timestamp' of date type"}}}}}
```

**Comment by dloy** [comment]
Three problems were identified with this error:
- log4j2 exception output in JSON includes a \n before the stack trace that causes a failure in logstash because every log entry must include @timestamp":"2023-... Because of the bad new line logstash fails.
- SDSC nodes are failing state commands. Not clear why this timing error exists.  The error occurs after an upload and the subsequent file metadata confirmation for the upload. Typically there is some elapsed time on one SDSC Minio server before the metadata for that file on another server is available. It appears to occur more frequently at SDSC now so the retry logic fails with 10 seconds.
- The storage microservice issues a state command attempt on the node when a GET file request is requested. This was an oversight when the state command change was put in.

Attempted Fix:
- log4j2 exception - change configuration for log4j2.xml to not allow stack trace to be treated as a json array, instead as a single message entry. stackTraceAsArray="false". The error also indicated the log4j2 text log did not include stack trace so added stackTraceAsArray="true" to the text log.
- SDSC nodes states failing - changed AWS logic to use longer retries - hopefully allowing upload logic to complete and metadata be retrieved.
- storage microservice node state on a file download - reviewing this logic to turn off the state validation during download.

**Comment by elopatin-uc3** [comment]
@dloy Thank you for the detailed problem descriptions and attempted fixes. It sounds like we should notify SDSC about the additional time you're seeing regarding the syncing of the metadata file across nodes. I can reach out to them if you'd like. Let me know.

**Comment by dloy** [comment]
Note: Error related to missing Metadata is the result of a bug in the Cloud code that does not trap a process error in an upload TransferManager. The actual error reports back a 404 status. This error should not occur in an upload unless the file to be uploaded does not exist. The occurrence of this error indicates a problem in constructing the uploaded content in the Minio handling.  See [mrt-cloud - TransferManager error #1661](https://github.com/CDLUC3/mrt-doc/issues/1661)
