### ISSUE TITLE
Zookeeper jar 3.8.3 is available (based on dependency scan meeting)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1728]

**Comment by elopatin-uc3** [comment]
This minor update has introduced a lot of debug logging. Mark is looking into how to handle this.

**Comment by mreyescdl** [comment]
More on debug messages.
Ingest build brings in the SLF4J jar.  This library is not explicitly defined in any of our POM files.

With Zookeeper jar 3.7.2 it brings in version "slf4j-api-1.7.35.jar" which cause an error which suppresses the DEBUG logs messages.
With Zookeeper jar 3.8.3 it brings in version "slf4j-api-1.7.30.jar" which allows the DEBUG messages to be shown.

I find if I explicitly define a newer version of in the Ingest POM, then JAR 3..3 works without debug messages.
See below.

I can add this to Ingest, but would it be better to add to "reflect/pom.xml" in Core??
What are your thoughts @dloy 

```
     <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.10</version>
    </dependency>
     <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>2.0.10</version>
    </dependency>
```

**Comment by mreyescdl** [comment]
https://github.com/CDLUC3/mrt-core2/pull/40
https://github.com/CDLUC3/mrt-core2/pull/41
https://github.com/CDLUC3/mrt-ingest/pull/96

**Comment by dloy** [comment]
The zookeeper debug logging issue that Mark ran into impacts all services using zookeeper: ingest, store, inventory.

The zookeeper jar explicitly includes org.slf4j:slf4j-api as a dependency.  It is not explicitly declared in the pom.xml for the Merritt services (including the BOM) which allows a secondary dependency to be used.  The zookeeper 3.8.3  jar ignores the service debug levels of slf4j2 and defaults to DEBUG - which cannot be overwritten.  As Mark determined, org.slf4j:slf4j-api:2.0.10 jar fixes this problem.

The fix for this is to explicitly include the org.slf4j:slf4j-api:2.0.10 and org.slf4j:slf4j-simple:2.0.10 jars in the dependencies for the source projects of the microservice and allow the version to resolve to the BOM as 2.0.10 version.

Thanks Mark for tracking this down!
