### ISSUE TITLE
UC3 AWS: Create Cloud Front Distribution for Merritt DEV resources

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1850]
### Public resources
| Repo | Path | Comment |
| - | - | - |
| mrt-zk | api/mrt-zk/java | |
| mrt-zk | api/mrt-zk/ruby | |
| mrt-core2 | api/mrt-core2/java | |
| mrt-cloud | api/mrt-cloud/java | |
| mrt-dashboard | api/mrt-dashboard/swagger | |
| uc3-ssm | api/uc3-ssm/ruby | |
| mrt-admin-lambda | doc/mrt-admin-lambda | Generated documentation about reports/actions |
| mrt-doc | app/manifest| Manifest valdiation tool |
| mrt-cron | presentation/mrt-cron/schema | Schema validation presentation |

### Private resources (Not immediately in scope)
- Use Cognito authentication
- Campus specific reports
- Static reports currently mediated through the admin tool (consistency reports)
- Private repo config file distribution

## Workflow
- Create new S3 bucket
- Create cloudfront resources for the bucket (Brian has examples)
- Push reports to S3

### propsed mrt-dev-public bucket
- these assets can be made public
  - the intended audience are Merritt depositors, Merritt team members, general open source community
- /javadocs
- /rubydocs
- /json-schemas
- /reveal-md
- /swagger 
- /manifest-tool

**Comment by terrywbrady** [comment]
@briri , fyi

**Comment by briri** [comment]
Ok, this looks like a lot but it's actually not too bad and I am happy to meet with you to walk you through everything (probably good to have Ashley join us too!)

Ashley will need to help you out with setting up a HostedZone. If she's busy feel free to just use ours in the dev account. You'll need to make your subdomain something like `mrt-docs.dmphub.uc3dev.cdlib.net` though.

If Ashley does create a HostedZone for you, you will need to create the following resources:
- [SSL cert](https://github.com/CDLUC3/dmsp_aws_prototype/blob/main/templates/cert.yaml)
- [Route53 Alias record](https://github.com/CDLUC3/dmsp_aws_prototype/blob/main/templates/route53.yaml)

You'll then want to create your S3 bucket and the CloudFront Distro:
- [S3 Bucket](https://github.com/CDLUC3/dmsp_aws_prototype/blob/816b9f9fd15e4aa5ecce9e31dde958f31ff4a750/templates/s3.yaml#L50) There are technically 2 you probably want. One for the website content and another for the access logs (optional). If you skip the log bucket, just comment out the references to it in the CloudFront template.
- [CloudFront Distribution](https://github.com/CDLUC3/dmsp_aws_prototype/blob/main/templates/cloudfront.yaml) Note that I keep my Swagger docs in an S3 "folder" `api-docs/`, so there is some JS logic in there that you may want to use for your implementation. 

Extra credit ;) You may not need it, but here is the [template for my WAF](https://github.com/CDLUC3/dmsp_aws_prototype/blob/main/templates/waf.yaml). If you don't use it, you'll want to comment out the references to it in the CloudFront Distro template

Then, I build my Swagger via a script that I run on my local that syncs the contents of the S3 bucket and then invalidates the CloudFront cache so that the changes are available immediately.

I'd recommend starting out with just a simple Hello World index.html file in your S3 bucket just to make sure that all the infrastructure is working
