### ISSUE TITLE
Examine "Merritt Storage Errors" query for last 30 days

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1990]
![Image](https://github.com/user-attachments/assets/130e0cc5-35d3-46f8-b38d-ffe4af8fe5a6)

**Comment by dloy** [comment]
Wasabi tech was asked about the existing 403 status errors. The response:
"The "Account Connection Limited" error occurs when the amount of concurrent requests from the client exceeds the allotted amount by our servers. This concurrent connection value is 10,000 connections (of all types) per account per region. When we see these issues, it is generally recommended that we scale back the number of concurrent requests to the region, or stagger the requests with a backoff algorithm once that upper value is reached."

Note that this problem occurs because of 5xx errors that frequently occur on the Wasabi East system. Here is that comment by wasabi:
"The non-fatal 5xx-HTTP errors do get retried and eventually succeed. With regards to the 410 and 400 HTTP errors, these are reported to be occurring due to the closure of open socket connections to our servers that have not been written to or read from within 60secs. Generally, these occur after a client-application initiates the connection closure (based on Application logic)."
