### ISSUE TITLE
Miscellaneous storage questions

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#21]
1. how can we mitigate the complexity of multiple storage technologies?
   1. what are the areas in which supporting multiple technologies becomes a
      problem?
   2. can we reduce the number of storage technologies we support?
2. what do we need to do to be able to move content w/o re-ingesting?

**Comment by dloy** [comment]
Carnegie: “Don’t put all your eggs in one basket” is all wrong. 
We tell you “put all your eggs in one basket, and then watch that basket.”

Comment:
Cloud technologies are an issue primarily because of differences in the handling of buckets. The swift openstack used by SDSC requires few files in a bucket but many buckets. AWS requires few buckets that can have large number of files. The success and failure of SDSC and AWS have similar problems that can be addressed a higher level.

One of primary features of ingest is to generate system files that contain descriptive information about the object that are then used by inventory in the database.
