### ISSUE TITLE
Presign UI Feedback

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#313]
## Wireframes link
- https://ux.cdlib.org/jlee/axure/merritt_06may2020/#id=hrye1y&p=object_landing_page_v4&g=2

## Notes from standup meeting
- [x] Update docker config with latest storage change
  - See #314 
- [x] Improve download link - does this make the Chrome log message go away
- [x] Remove download page
- [x] Add unit tests
- [x] Document javascript code

## Eric and Terry review on 5/8
- [x] Firefox download issue
- [x] Set meaningful name to download file
- [x] Animate 90% to 100%
- [x] Add logging to see how many 202 tries are needed for an object
- [x] Set dial to back off the 20sec minimum to improve accuracy
- [x] Put title in h3, truncate to max length
  - Jane recommends using an H1 and then styling it.  Truncate the title with code or CSS and add ...
- [x] Download Pending - change to percent
- [x] Item with LOTS of files, took longer to download - inform David that this might need to be part of the time calculation

## Questions for Jane
- [x] Add download icons / controls
- [x] Improve look of Cancel/Continue buttons
- [x] Mobile usage - do the modal boxes introduce an issue
  - Set the modal to fit within a smaller size.  Otherwise, do not attempt to solve other mobile issues
- [x] Style download button w/ background and outline to look like a button

## Accessibility feedback on 5/21
- [x] Screen reader of progress bar label?
  - the label has an aria-label, does that label need to be marked as _for_ the progress bar?
  - _added a for attribute. voiceover does read the label for me_
- [x] Change modal title: Preparing Object/Object Ready/Object Downloaded
- [x] Can modal title be an h2?
  - **not supported in jqueryui**
- [x] Object title should be an h3 in modals
- [x] Change text: "Your object is ready for download: _filename_"
- [x] Add Download button to tab index
- [x] If user re-attempts to download the same object, do not present the Cancel/Continue screen
- [x] Contact Jane next week to run full accessibility test
- ### General Accessibility Issues (new tickets needed)
  - Add site skip to man content
  - Bump all h2 to h1 and all h3 to h2 in the app

**Comment by terrywbrady** [comment]
@elopatin-uc3 , fyi

**Comment by elopatin-uc3** [comment]
@terrywbrady I found an issue with the the object download dialog that I think is an edge case. I don't think we need to address this, because it doesn't prevent a user from obtaining a zip. But wanted to mention it either way. Here are the steps to reproduce:

1. Go to an object page and click Download object.
2. While the download is in progress, click the Preparing Download dialog's Close button and wait until the download completes.
3. Click Download object again, and choose to Download Current Object. At this point the preparing Download dialog starts at 90%, and moves to 100%.
4. Click the Close button.
5. Click the Downloads: Available button.

Result – When you click the Downloads: Available button in step 5, the progress bar resets to somewhere less than 90% and continues until finished.
