### ISSUE TITLE
File download/presign encoding errors have resurfaced

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#356]
The presign object/version changes may have overwritten a prior fix for the character encoding issue.

```
 URI must be ascii only "/api/presign-file/ark:%2F13030%2Fm5s51tz3/1/producer%2Fjavoi\u0161_et_al_data.xls?no_redirect=true"

  /apps/dpr2/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:21:in `split'
```

Check for https://github.com/CDLUC3/mrt-dashboard/pull/56/files in code base.

## Investigate (note the filename in this object)
- [ ] https://datadryad.org/stash/dataset/doi:10.5061/dryad.q2cc41c (error)
- [ ] https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5s51tz3/1 (no error)

## We had a similar issue in early April with this object.  Note that this works
- https://datadryad.org/stash/dataset/doi:10.5061/dryad.0k0mt
- https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5sf7w9f/1

**Comment by terrywbrady** [comment]
@sfisher,

My fix does not resolve the issue that we saw yesterday.  The Merritt UI and the Dryad UI are requesting the file retrieval with different url encodings.  The Merritt UI version is working.

### Dryad approach
```
Started GET "/api/presign-file/ark:%2F99999%2Ffk44x6n827/1/producer%2Fjavoiš_et_al_data.xls?no_redirect=true" for ...
```

## Merritt Approach
```
Started GET "/api/presign-file/ark%3A%2F99999%2Ffk44x6n827/1/producer%2Fjavois%CC%8C_et_al_data.xls" for ...
```

**Comment by sfisher** [comment]
Hi Terry,

I've narrowed this problem down to the gem `http.rb`.  It is somehow messing up the encoding and the URLs it is sending.  The URL we are generating works both in CURL and also in another http library like HTTParty and the URL I am generating is correct.

It was incredibly difficult to track down because it is both following redirects (which change the URL to double-encoding which was a nice red herring) and the change seems to be very, very small and not even visible outside of the http.rb library in certain cases.

```
# this works
https://merritt.cdlib.org/api/presign-file/ark:%252F13030%252Fm5s51tz3/1/producer%252Fjavois%cc%8c_et_al_data.xls?no_redirect=true

# this doesn't
https://merritt.cdlib.org/api/presign-file/ark:%252F13030%252Fm5s51tz3/1/producer%252Fjavoi%c5%a1_et_al_data.xls?no_redirect=true
```

Do you see the difference?  One has `javois` in it and one only has `javoi` in it before the encoded characters.  Those are the URLs that were produced after all redirects by CURL (first one) and http.rb (second one).

The even crazier thing is that `http.rb` still fails even with the correct https URL and *absolutely NO redirects* and for all you can see, the URL is completely correct, but it is obviously really botching something up badly internally.

I eventually tried with the HTTParty gem instead and it actually handles the URL correctly and returns the correct results instead of a 404.

So . . . you managed to find a low-level bug in a gem.  :-/

Though I still believe something is screwy with the Merritt redirects, even though it handles it somehow.  I mean should the ARK get encoded an extra time just because it redirects from http to https?  I think this might be an apache thing with NE flag missing for the rewrite rule, but I'm not sure of that.
