### ISSUE TITLE
Track Dryad dataset copies in Zenodo, using an identifier provided by Zenodo.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#358]
### Summary
Now that Dryad's implementation of sending dataset copies to Zenodo is complete, we need to start tracking said copies.

###
Tasks
- [ ] Determine how to obtain appropriate PID from Zenodo, and where to store this in the Merritt Inventory database.
- [ ] Determine the best approach to harvest PIDs on a regular basis.
- [ ] Consider both new item and backfill use cases
- [ ] Prototype and then implement a solution for obtaining the PID and storing it.

**Comment by terrywbrady** [comment]
Terry and David discussed this.

## Assumptions
- The Zenodo copy is not a Merritt replication.  It cannot be accessed by Audit or Replication.
- The Zenodo copy maps to an Merritt Version (Ark + Version Number)
- This information would not live in Merritt cloud storage.  
- This information would simply exist as documentation field in the Merritt database.

## Questions
- Since this information exists in the Dryad database, what is the motivation for storing this in the the Merritt database?
- What functionality is expected from Merritt?
  - Audit: not supported
  - Replication to Zenodo: not supported
  - Replication from Zenodo: not supported 

## Options
- Dryad deposits to Zenodo first and then includes the Zenodo URL in object metadata (unrealistic)
- Create a new table inv_objects_documentation OR inv_objects_provenance to store this (and other) information
 - Add Merritt API endpoint to read/write this information
 - Add Merritt API endpoint to read/write this information on behalf of a client application - this is opaque information maintained by the client (Dryad) 
 - Force a Merritt version update to an object in order to contain this information as metadata (complicates version tracking for Dryad)

## Other types of documentation/provenance information to track
- Record known issues with specific objects
- Record manipulation performed on object (provenance)
- Record deletion/tombstone information

**Comment by sfisher** [comment]
This is just some information from our meeting.

- We are talking about data replication to Zenodo, not about software or supplemental deposit to Zenodo which is something else and is completely managed by them.  Allowing people to make these deposits is just a convenience for our users and they are Zenodo deposits.
- The same DOI from Dryad is logged at Zenodo and it can be searched or looked up there to find the copy we have there.
- All user submitted datasets from Dryad is sent to Merritt and there are multiple versions.  (We do take and manage files before submission.)
  - The Dryad public view only shows the latest embargoed/published *metadata* (but more is in the database).
  - The public view in Dryad shows multiple versions of data files if more than one has been published and the files changed between published versions.
- What is replicated for data submissions at Zenodo is ONLY the latest published version.
  - Any previous published version is updated/overwritten at Zenodo by a later published version.
  - It is not sent to Zenodo until it is published, so unpublished works in Merritt are not replicated.
  - These replication practices were set as the requirements for the data (vs software/supplemental) portion of the project when we met with Zenodo at the start of the project.
  - Zenodo modified their normal API and workflow to fit the defined requirements by allowing us to re-open published works, make modifications and re-publish the same item.  (To only have the latest published version of data submissions replicate there.)

**Comment by elopatin-uc3** [comment]
Thanks @sfisher for the above notes.
