### ISSUE TITLE
Audit Fixity Error on July 14

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#407]
Fixity: periodic report: ERROR(S) detected - failed:3 - unavailable:0

- is this due to the disabled audit services?

**Comment by dloy** [comment]
## Problem
3 audit failures occurred for the same object-version: 
id: ark:/13030/m5xm3p9d

version: 5

Files:
- system/mrt-ingest.txt
- producer/stash-wrapper.xml
- system/mrt-submission-manifest.txt

Localids:
ark: ark:/13030/m5xm3p9d
owner: ark:/13030/j28910x4
localid: doi:10.5068/D16T06
created: 2020-07-09 11:14:43


## Errors
See attached
[analysis.txt](https://github.com/CDLUC3/mrt-doc/files/4948858/analysis.txt)

## Analysis
The manifest.xml data for all of the error files contains the correct manifest shown in the error. The inv db was loaded from a manifest.xml that no longer exists and was submitted a day after.

Date for audits entry creations:
2020-07-13 13:13:21

Date for manifest enries:
2020-07-12T01:50:30-07:00
2020-07-09T11:14:43-07:00
2020-07-12T02:22:33-07:00

mrt-dc.xml for 5th version corresponds to 1st version so 5th appears to be a correct version update to this ark. stash_wrapper.xml for 5th version  matches 4th version - again a correct version update to this ark.

The timing on these fields indicates that an initial manifest was issued as a 5th versions.  A new update to that object was issued and completed before the the earlier version completed. The earlier version the manifest.txt.

### Analysis data
[analysis.txt](https://github.com/CDLUC3/mrt-doc/files/4949835/analysis.txt)

### Solution
Resubmission of the overwritten update - might be possible - otherwise manual db replacements for the existing digest values could be done.
