### ISSUE TITLE
Notifier errors -- handle URL's with improperly encoded arks?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#442]
There are lots of these errors for downloads and presigned file requests.

It is unclear if these are generated by scraping.

- [ ] determine if the atom feed contributes to this error

```
  get('api/presign-file/ark:/*path' => 'file#presign_path', :format => false, :as => 'presign_file_path')
  get('api/presign-file/:object/:version/*file' => 'file#presign', :format => false, :as => 'presign_file')
```

## Example
- https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t16 (Errors)
- https://merritt.cdlib.org/m/ark:%2F13030%2Fm5j72jfz (Does not error)
```
Parameters : {"no_redirect"=>"true", "controller"=>"file", "action"=>"presign", "object"=>"ark:", "version"=>"13030", "file"=>"m5j72jfz/1/producer/ Müller et al. 2016 Journal of Ecology (2) seeds.xls"}
```

**Comment by terrywbrady** [comment]
This appears to resolve the issue
https://github.com/CDLUC3/mrt-dashboard/commit/51484f92097ddb3d9c3973e6053eeaeb8ae65af4

**Comment by sfisher** [comment]
Hi Terry,

It looks like the one you mentioned at https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t16 was failing because of an extra space in front of the filename in our database compared to the version in Merritt.  It looks like this was probably migrated incorrectly from the old Dryad system.  I'll put in a ticket to look for these types of issues to fix.

We originally got this error.

```
 Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5j72jfz/1/producer%2F%20Mu%CC%88ller%20et%20al.%202016%20Journal%20of%20Ecology%20%282%29%20seeds.xls?no_redirect=true
Http status code: 404
```

But it works when removing the extraneous space in the filename, so doesn't seem to be so much an encoding issue as an issue where the filenames between the two systems didn't match up.  I'm not sure if there are other problems in there.

**Comment by sfisher** [comment]
See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/836 for the extra space one from our UI.
