### ISSUE TITLE
Identify local ids with more than one ark

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#472]
The following query isolates this for Dryad (43,000 objects).

https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src/queries/doi_conflict_query.rb#L12-L29

In production, there are 1.7M + local ids and they are only unique across inv_owner_id.

I attempted to apply the same logic to all local ids, but it was prohibitively slow.  

If we need to isolate this issue, we would need to do the following:

- Create a temp table containing local_id and an ark
- Load the local ids (from inv_objects) into the temp table
- Create an index
- Query for duplicates

## Options
- replace this temp table daily?
- iteratively load new entries from inv_objects/inv_localids into this temp table

Note that the inv_localids table is intended to serve this purpose, but it seems like the duplicate key check built into this table prevents the conflicting id from getting loaded into this table.

## Caution: 
If we proceed with this work, we should test the process in a cloned RDS server in order to optimize the processing of the 1.7M keys

**Comment by sfisher** [comment]
Hi @terrywbrady 

Excuse the tangential comment, but perhaps some of these issues might have been prevented in the Dryad case, using SWORD, by returning errors rather than creating new ARKs on REST *put* requests.

I verified that we send different kinds of REST requests to SWORD based on whether something is an *update* to an existing dataset (*put* request) or a *new* dataset (*post* request).  When a *put* request comes in and an existing dataset or ARK cannot be found, I'd rather get an error back than a new dataset since we don't expect or want a new one from that kind of request.

Maybe it's more complicated than that and there is some situation where the *put* request does an upsert (insert with specified id), but I don't think we use it that way.

Anyway, just a thought and I think it may be a simple validation from SWORD (depending how the code is structured).

**Comment by sfisher** [comment]
I may add a new issue with this info and then let you decide if it's something that is feasible or worth fixing.  I think it may save us some time in the future if it's an easy fix.

**Comment by dloy** [comment]
Tried to detect these objects by seeing which objects were not in inv_localids table. The issue there is that if the object does not have a local id it does not appear in this table. It brings up a question, whether we have duplicates "objects" when secondary versions do not include an objectid nor localid.

**Comment by terrywbrady** [comment]
@dloy , we do have records in the inv_objects table which I think is more definitive than the localid table.

https://merritt-admintool.cdlib.org/index.html?path=doi

**Comment by elopatin-uc3** [comment]
See also #464 and #473

**Comment by terrywbrady** [comment]
Report now exists.  This has not been an issue in a while
