### ISSUE TITLE
Remaining 40K file object for replication to Wasabi

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#477]
We've had a handful of failures show up in the Inventory queue report since August 13th. We should investigate these and ensure they complete the entire ingest process.

~~~
mrtQ-000001165844: [failed: Thu Aug 13 09:54:56 PDT 2020] {manifestURL=http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc}

**Comment by elopatin-uc3** [comment]
`ark:/13030/m5r269bc` has been stuck in the Inventory queue for a very long while now. However I believe it is not the 40K object that can't be replicated to Wasabi. That object is likely `ark:/13030/m5q57br8`. To view, sort the results of the Objects - File Copies Needed - Older than 0 days" report by File Count:
https://merritt-admintool.cdlib.org/index.html?path=file_copies_needed&days=0&limit=500

**Comment by dloy** [comment]
mail to wasabi:

~~~
 Sep 28, 2020, 20:19 EDT

I am getting the following error when attempting a POST to S3:

com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service:
Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID:
392A6BA1CCB656FA; S3 Extended Request ID:
Dsw6eEpHYdv7Qf2EJ7eHXBmTAnvkAwO5JRN0KH/kgi03mKHePN6YqTrwTfq68rVd73n+o5p5DRrE),
S3 Extended Request ID:
Dsw6eEpHYdv7Qf2EJ7eHXBmTAnvkAwO5JRN0KH/kgi03mKHePN6YqTrwTfq68rVd73n+o5p5DRrE

This error occurs when attempting to POST using the following key (in
http encoding):

ark%3A%2F13030%2Fm5q57br8/1/producer%2FTLP%20photographs%20-%20Jacques%20Garnier%2FMCAS%20ET%202009%2FGreat%20Picture%20images_shortlist%20_2%20-%20%20%2FGreat%20Picture%20images_shortlist%20_2%20historical%20images%2FDaguerre%EF%BF%BDparis%EF%BF%BDstreet.jpg";

The error occurs because of the UTF8 characters:%EF%BF%BD = |�|

|This is a legal UTF8 and is supported in AWS S3.
|

|Can you tell me any workarounds to get this to work on your system?
|

|Thanks|

|David Loy|
~~~

Current response:
~~~
 Pankaj @ Wasabi Support (Wasabi Technical Support)

Jun 22, 2021, 11:52 EDT
Hi David -      thanks for your patience, this defect is currently not fixed yet and I do not have a timeline to share for now. I can touch base again proactively once I get any update on the code change timeline to address this

-Pankaj
~~~

**Comment by terrywbrady** [comment]
https://codepoints.net/U+FFFD?lang=en

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think you took the TODO to see if we can re-submit a corrected object with a new ark.

**Comment by elopatin-uc3** [comment]
Noting the image in question: Daguerre_paris_street.jpg
and unescaped URL, generated via https://www.utilities-online.info/urlencode:
photographs - Jacques Garnier/MCAS ET 2009/Great Picture images_shortlist _2 -  /Great Picture images_shortlist _2 historical images/Daguerreï¿½parisï¿½street.jpg

**Comment by elopatin-uc3** [comment]
Message sent to EA-R at UCI, asking for permission to revise the name of the file in question.

Possible actions to take to revise the object:
- Extract manifest
- Edit out the errant file
- Use the manifest for the new ingest
- Add the renamed file as an update
- Delete the old object

**Comment by elopatin-uc3** [comment]
@terrywbrady @dloy UCI's archivist for University Archives has approved changing the file name. We should see if we can address this next sprint by downloading the object, revising the file name and resubmitting under a new ARK.

**Comment by elopatin-uc3** [comment]
Resubmission underway on ingest01:
bid-db10d2b4-22c9-436a-b777-d09746ee22e0

**Comment by elopatin-uc3** [comment]
Still processing; 474G as of 4/27, 11:45am

**Comment by elopatin-uc3** [comment]
Delete completed successfully. delete file name on store05 is wasabi_issue_477.txt.
