### ISSUE TITLE
UI server issues filling root volume with a puma file.  

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#520]
This happened to ui03 and ui02 on Nov 4.

On ui03, with a note from Martin:
```
-rw------- 1 dpr2 dpr2 8261959680 Nov  4 17:35 puma20201104-3021-1xce8d3
```
(from Martin):
I spotted an 8 GB file `/tmp/puma20201104-3157-x35122`... not sure what the file is, but I moved it to `/apps/dpr2/puma20201104-3157-x35122` so you can still check it out.

**Comment by mreyescdl** [comment]
Production and Stage UI environments differ for where uploaded (payload) content is written.
For stage, it is written to /dpr2/tmpdir (1 TB disk) but on prod it is written to /tmp (12GB)

It looks like the is due to the absence of directory /dpr2/tmpdir on production.  If this directory exists, I believe that Rails would write data there due to the following in environment.rb

```
ENV['TMPDIR'] = Rails.root.join('/dpr2/tmpdir').to_s unless ENV['RAILS_ENV'] == 'test'
```

I'd like to create this directory on UI03 and restart the service to see if this is true.

**Comment by elopatin-uc3** [comment]
Glad you were able to diagnose this @mreyescdl. I'm really surprised we hadn't seen any troubles with the 12GB temp space in production beforehand.

**Comment by mreyescdl** [comment]
Created /dpr2/tmpdir on all three workers.  Restarted 2 an 3 but not 1.  All three seem to now use /dpr2/tmpdir for temp space.  Most submission traffic seems to go to ui01.  Not sure why.  Maybe look into Apache LB rules we have in place

Let's monitor for a day or two.

**Comment by mreyescdl** [comment]
@elopatin-uc3 I think because the payload is usually a manifest, which is not large.

One of the failed submissions which did trigger the error was named "Hood_AIP.zip"  I was unable to trace where it came from.  The other submission I was unable to find the payload file.  Maybe it was a retry of "Hood_AIP.zip"

**Comment by terrywbrady** [comment]
@mreyescdl and @elopatin-uc3 , I propose closing this since the underlying UI deploy has changed significantly

**Comment by elopatin-uc3** [comment]
Closing this sounds fine to me @terrywbrady
