### ISSUE TITLE
Cloud yaml tweak for stage only, to enable eSchol ETD harvester testing

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#638]
Noting Pivotal ticket:
https://www.pivotaltracker.com/story/show/173948624

On stage, the eSchol ETD harvester receives a 503 service unavailable from SDSC. This is due to the port number appearing (443) in the Host header of the request. This configuration information, with port number can be modified for stage only. Ultimately, SDSC will make a change on their side to remove the port number.

#### Tasks
-  [ ] Remove port number from cloudConfig.yml for stage only

**Comment by dloy** [comment]
The problem occurred;
- request for download is sent to UI
- UI calls storage to get presign embedded in a JSON response
- storage calls an SDSC cloud service requiring a :443 in the end point for the cloud
- storage returns the presign with :443 in URL
- UI extracts the presign URL and and returns it to the user as redirect to the presign
- the presign response contains the end point :443 
- the redirect issues a HOST header that contains the :443 with the server (<server>:443)
- SDSC fails any response HOST with a port number

2 solutions are being performed:
1. have the ingest use AWS instead of SDSC for the primary for ucsf etd collection
2. request SDSC to "tweek" the front end rules to the minio service to support a :443 as a HOST port

**Comment by elopatin-uc3** [comment]
SDSC change is no longer needed. We worked around this problem by reconfiguring the stage collection to use S3 as its primary storage node.
