### ISSUE TITLE
UC Data Migration to Dryad not reproducing some history correctly

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#649]
**Describe the bug**
This is version 4 of the dataset in the Dryad collection after it was migrated:  https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5cs1fjn/4

This is version 4 of the same dataset in the UCSB collection where it originally lived:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm59w5p09/4

Version 4 in the Dryad collection has many more files and the `mrt-delete.txt` is also not present, so it doesn't seem like the deletions in version 4 were replicated correctly into the Dryad collection version.

IDK if this is a general problem with all datasets or just this one.

Luckily if it is only deletions that are missing then there is likely no loss of data because of the problem.  We also have versioning history in our own database which only exposes files we believe to be present in a version.  It was very confusing to see all these deleted files show up again in Merritt when I expected them to be gone in version 4 and afterward.

**Screenshots**

UCSB merritt collection:
![Screen Shot 2021-04-20 at 1 29 52 PM](https://user-images.githubusercontent.com/105433/115460922-b4e9d600-a1dd-11eb-821c-e006c7cd26db.png)

Dryad merritt collection for the same object:
![Screen Shot 2021-04-20 at 1 30 23 PM](https://user-images.githubusercontent.com/105433/115460990-c632e280-a1dd-11eb-96b1-5cc3086f4079.png)

We might want to do some careful validation before deleting any of the old UC collections.

**Comment by dloy** [comment]
The above occurs because the delete.txt files for updates to certain objects were not applied. All of the content survived this process - but the content of any specific version was not reflected.
[unprocessed-deletes.txt](https://github.com/CDLUC3/mrt-doc/files/6361843/unprocessed-deletes.txt)

**Comment by elopatin-uc3** [comment]
Documented options:
https://confluence.ucop.edu/display/~tbrady/Dash-%3EDryad+Migration+Options

**Comment by elopatin-uc3** [comment]
From @dloy:

This process creates a new Storage manifest.xml corresponding to Dryad - apply a localized removal of a file on specific versions,

Once a "correct" Merritt version exists then the Merritt system would need to be adjusted to allow the changes to be reflected in the inv db, all Merritt replications.

Working on this approach has shown that several new Dryad objects cannot have earlier versions adjusted using this approach because certain files were added to Dryad much later than they were added to Merritt. Examples include a file included in version 1 of Merritt and showing up in version 5 of Dryad. Adjusting manifest.xml is doable - manifest.xml now exist reflecting the needed
changes.

The most difficult problem in addition to changing the manifest.xml is how to apply these fixes to get Merritt to correctly look like Dryad (for current only).

This fix requires:

replace the manifest.xml for all primary objects - this includes
add manifest.xml as manifest-original.xml
delete manifest.xml
add updated manifest.xml
delete secondary content
delete inv db
add to inventory. This will:
kick in automatic replacement of secondary content with automatic update of audit
Discussions with Scott about his original Plan C - add a corrective ingest version to fix these problems on Merritt would be a substantial fix on Dryad. Should not be done. So proceeding with this task as originally planned.
