### ISSUE TITLE
Coll admin: Endpoints to generate SLA, Owner and Input profile objects

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#657]
Reference (see Not Yet Implemented section):
https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-colladmin
See also #488 

With ARK input from EZID, as well as collection documentation (name, mnemonic, node, contacts), generate a SLA, Ownership and Input collection object text to be displayed in browser. Text will be copied/pasted for commit into github mrt-ingest-profile repo.

Generate Profile Object 
- User will manually commit to git
- Colladmin
  - POST
- Steps
  - Get EZID
  - ??

Generate Ownership Objct
- User will manually commit to git
- Colladmin
  - POST
- Steps
  - Get EZID
  - ??

**Comment by elopatin-uc3** [comment]
Noting PR for the addition of validation to the profile creation API:
https://github.com/CDLUC3/mrt-ingest/pull/20/

**Comment by mreyescdl** [comment]
Deployed to Stage Ingest01 and Ingest02

Running a full profile request will now spit out an error (Log on host and run "curl --silent http://localhost:33121/admin/profiles-full?t=xml")

Error is due to the more stringent processing of Ingest profiles (e.g. TimeZone in dates)
We'll need to modify the profiles on stage.
