### ISSUE TITLE
UCSC submission fails with malformed zip error

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#864]
The zip in the following manifest fails to ingest due to a 'MALFORMED' error:

```
#%checkm_0.7
#%profile | http://uc3.cdlib.org/registry/ingest/manifest/mrt-container-batch-manifest
#%prefix | mrt: | http://merritt.cdlib.org/terms#
#%prefix | nfo: | http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#
#%fields | nfo:fileUrl | nfo:hashAlgorithm | nfo:hashValue | nfo:fileSize | nfo:fileLastModified | nfo:fileName | mrt:primaryIdentifier | mrt:localIdentifier | mrt:creator | mrt:title | mrt:date
https://transfer.library.ucsc.edu/MS323_AIP.zip |  |  |  |  | MS323_AIP.zip |  | MS323 | White, Hayden V., 1928-2018 | Hayden V. White papers: born-digital | 2000-2011
#%eof
``` 

#### Tasks
- [x] Manually download and unzip
- [ ] Using the object-level metadata found in the manifest, re-zip and attempt to resubmit via the UI to the UCSC Library Special Collections collection: https://merritt.cdlib.org/m/ucsc_lib_sc

**Comment by mreyescdl** [comment]
I was able to unpack ZIP file copied from there server with both Linux zip utility and Java library.
See work on any production Ingest server at */dpr2/ingest_home/queue/tools/unzip_test*

If user decides to have Ingest unpack, we can resubmit and see what error occurs during Ingest.

**Comment by elopatin-uc3** [comment]
Thanks for the update @mreyescdl

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Hi Eric,
It turns out if we want to unpack this large zip we'll need to change the zip container.  First unpack it with character encoding "ISO-8859-1"  and then repack it with "UTF-8."
Production Merritt unpacks with UTF-8, so barring a code change we'll need to do the above.  Of course, this modifies the initial submission payload.

Reading through Kate's initial email, it sounds like she is okay to submit this as a large container (unzipped)
Is it okay to submit it this way?  It sounds like the cleanest approach.

**Comment by elopatin-uc3** [comment]
@mreyescdl  Thanks for determining what we would need to do, with regard to changing the character encoding. Based on Kate's messages, it should be fine to submit this as a large container that's unchanged. Please go ahead and give that a try. Thanks!

**Comment by mreyescdl** [comment]
Here is the object Eric.  Thanks

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5k1421s
