### ISSUE TITLE
[RELEASE] Merritt UI: Clustered Mode 12/1 at 4pm

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#867]
# Service(s)
Merritt UI

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/724

# Servers affected
ui03
ui04
ui05

# Source Code:
https://github.com/CDLUC3/mrt-dashboard/pull/110

# Jenkins/Build Info: (if applicable)

# Deployment Steps (if applicable)
- Tag new branch
- Update hiera config for ui prod and ui05
- Run puppet deploy for each server

# Infrastructure Changes to support deployment (ALB, EFS, etc)

**Comment by mreyescdl** [comment]
Note:  Will update Puppet revision and commit, but not check into Puppet repo.
This will allow for manually applying Puppet change for each host, when it has been removed from ALB
I will start with UI05 and confirm deployment through preview endpoint

After all hosts are deployed then push of Puppet code can take place, but will not cause a redeployment (since it was done manually)

**Comment by mreyescdl** [comment]
Deployment complete v1.0.23
Unit tests completed okay

Lesson learned:  Do not try and bypass Puppet method Ashley has put in place.  Upgrade using her method is very fast!
