### ISSUE TITLE
Document a smoke test suite for UI and Ingest

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#97]
#### Summary
In order to consistently exercise existing UI and Ingest functionality ahead of patch deployment, we need a smoke test suite which documents associated integration tests.

#### AC
* A confluence page is established which documents all integration (functional) tests
* Tests incorporate introducing a new collection
* Edge cases are included in the suite, which introduce small and very large objects as part of the collection
* Display of collection file and system file line items in the UI are checked
* More than one version of the collection is generated (a total of two should be fine)
* Cases which entail the download of all objects are included in the suite
* The breadth of functional tests considers unit test implementation, in order to provide tightly-coupled  test coverage (with reason). 
* Completed test suite is reviewed by the team for feedback.

#### Notes
* ...

 - [ ] Draft test cases and loosely determine overall coverage
 - [ ] Review unit test coverage with dev
 - [ ] Create test collection with objects that range in size from small to very large
 - [ ] Work through tests on Stage
 - [ ] Team review and feedback

**Comment by elopatin-uc3** [comment]
Test comment

**Comment by terrywbrady** [comment]
The https://github.com/CDLUC3/merritt-docker repo provides a framework that might be useful for these tests.  
- Uses a database housed in a container and persisted to a docker volume
- Uses storage housed in a container and persisted to a docker volume
- Can also run a similar configuration for some Dryad services
- Note: this process still relies on the LDAP service and some id minting services

Since the content is housed in docker volumes, those volumes can be created and destroyed at the start of each test suite.

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-integ-tests
